using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dashboard.Services;

public class PtoService
{
    private readonly AppDbContext _db;

    public PtoService(AppDbContext db)
    {
        _db = db;
    }

    public async Task InitializeDatabaseAsync()
    {
        // EnsureCreated skips if ANY tables exist. 
        // We force the new tables into the existing DB using raw PostgreSQL commands.
        var sql = @"
            CREATE TABLE IF NOT EXISTS ""PtoPolicies"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""UserId"" integer NOT NULL,
                ""Year"" integer NOT NULL,
                ""TotalAllowanceHours"" numeric NOT NULL,
                ""CarryOverHours"" numeric NOT NULL,
                ""HoursPerWorkDay"" numeric NOT NULL,
                ""Interval"" integer NOT NULL,
                ""AccrualStartDate"" timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_PtoPolicies"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""PtoEntries"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""PtoPolicyId"" integer NOT NULL,
                ""Date"" timestamp with time zone NOT NULL,
                ""Description"" text NOT NULL,
                ""Amount"" numeric NOT NULL,
                ""EntryType"" integer NOT NULL,
                ""Status"" integer NOT NULL,
                ""Notes"" text NOT NULL,
                CONSTRAINT ""PK_PtoEntries"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_PtoEntries_PtoPolicies_PtoPolicyId"" FOREIGN KEY (""PtoPolicyId"") REFERENCES ""PtoPolicies"" (""Id"") ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS ""IX_PtoEntries_PtoPolicyId"" ON ""PtoEntries"" (""PtoPolicyId"");
        ";

        await _db.Database.ExecuteSqlRawAsync(sql);
    }

    public async Task<PtoPolicy?> GetPolicyAsync(int userId, int year)
    {
        try
        {
            return await _db.PtoPolicies
                .AsNoTracking()
                .Include(p => p.Entries)
                .FirstOrDefaultAsync(p => p.UserId == userId && p.Year == year);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"PTO GetPolicy Error (Likely missing table): {ex.Message}");
            return null;
        }
    }

    public async Task<PtoPolicy> CreatePolicyAsync(PtoPolicy policy)
    {
        _db.PtoPolicies.Add(policy);
        await _db.SaveChangesAsync();
        return policy;
    }

    public async Task<PtoPolicy> UpdatePolicyAsync(PtoPolicy policy)
    {
        _db.PtoPolicies.Update(policy);
        await _db.SaveChangesAsync();
        return policy;
    }

    public async Task<PtoEntry> SaveEntryAsync(PtoEntry entry)
    {
        if (entry.Id == 0)
        {
            _db.PtoEntries.Add(entry);
        }
        else
        {
            _db.PtoEntries.Update(entry);
        }
        await _db.SaveChangesAsync();
        return entry;
    }

    public async Task DeleteEntryAsync(int id)
    {
        var entry = await _db.PtoEntries.FindAsync(id);
        if (entry != null)
        {
            _db.PtoEntries.Remove(entry);
            await _db.SaveChangesAsync();
        }
    }

    /// <summary>
    /// Deletes any existing 'Accrual' entries for the policy year and generates a fresh schedule.
    /// </summary>
    public async Task GenerateAccrualScheduleAsync(int policyId)
    {
        var policy = await _db.PtoPolicies.FindAsync(policyId);
        if (policy == null) return;

        // 1. Remove existing auto-generated accruals
        var existingAccruals = await _db.PtoEntries
            .Where(e => e.PtoPolicyId == policyId && e.EntryType == PtoEntryType.Accrual)
            .ToListAsync();
            
        _db.PtoEntries.RemoveRange(existingAccruals);
        await _db.SaveChangesAsync(); // Save to clear the ledger

        // 2. Generate dates based on the interval
        var accrualDates = new List<DateTime>();
        
        // Ensure UTC to prevent PostgreSQL timezone mapping errors
        DateTime currentDate = DateTime.SpecifyKind(policy.AccrualStartDate, DateTimeKind.Utc);

        while (currentDate.Year == policy.Year)
        {
            accrualDates.Add(currentDate);

            switch (policy.Interval)
            {
                case PtoAccrualInterval.Weekly:
                    currentDate = currentDate.AddDays(7);
                    break;
                case PtoAccrualInterval.BiWeekly:
                    currentDate = currentDate.AddDays(14);
                    break;
                case PtoAccrualInterval.Monthly:
                    currentDate = currentDate.AddMonths(1);
                    break;
                case PtoAccrualInterval.SemiMonthly:
                    // Usually 1st and 15th
                    if (currentDate.Day < 15)
                        currentDate = new DateTime(currentDate.Year, currentDate.Month, 15, 0, 0, 0, DateTimeKind.Utc);
                    else
                        currentDate = new DateTime(currentDate.Year, currentDate.Month, 1, 0, 0, 0, DateTimeKind.Utc).AddMonths(1);
                    break;
                case PtoAccrualInterval.Annually:
                    currentDate = currentDate.AddYears(1); // Will exit loop immediately
                    break;
            }
        }

        // 3. Calculate hours per drop and create entries
        if (accrualDates.Count > 0)
        {
            decimal hoursPerDrop = Math.Round(policy.TotalAllowanceHours / accrualDates.Count, 2);

            foreach (var date in accrualDates)
            {
                _db.PtoEntries.Add(new PtoEntry
                {
                    PtoPolicyId = policyId,
                    Date = date,
                    Description = "Scheduled Accrual",
                    Amount = hoursPerDrop,
                    EntryType = PtoEntryType.Accrual,
                    Status = PtoEntryStatus.Approved // Accruals are considered approved/posted
                });
            }
            await _db.SaveChangesAsync();
        }
    }
}